// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: spec/warehouse-service.proto

package warehousepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_spec_warehouse_service_proto protoreflect.FileDescriptor

const file_spec_warehouse_service_proto_rawDesc = "" +
	"\n" +
	"\x1cspec/warehouse-service.proto\x12\twarehouse\x1a\x14spec/warehouse.proto\x1a\x1bgoogle/protobuf/empty.proto2\x86\x03\n" +
	"\tWarehouse\x12I\n" +
	"\rGetKnownNodes\x12\x16.google.protobuf.Empty\x1a .warehouse.GetKnownNodesResponse\x12D\n" +
	"\x0fPulseNodeToNode\x12\x17.warehouse.PulseRequest\x1a\x18.warehouse.PulseResponse\x12F\n" +
	"\fStorageStore\x12\x1e.warehouse.StorageStoreRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vStorageLoad\x12\x1d.warehouse.StorageLoadRequest\x1a\x1e.warehouse.StorageLoadResponse\x12R\n" +
	"\rStorageDelete\x12\x1f.warehouse.StorageDeleteRequest\x1a .warehouse.StorageDeleteResponseB\x1dZ\x1bpkg/service/api/warehousepbb\x06proto3"

var file_spec_warehouse_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),         // 0: google.protobuf.Empty
	(*PulseRequest)(nil),          // 1: warehouse.PulseRequest
	(*StorageStoreRequest)(nil),   // 2: warehouse.StorageStoreRequest
	(*StorageLoadRequest)(nil),    // 3: warehouse.StorageLoadRequest
	(*StorageDeleteRequest)(nil),  // 4: warehouse.StorageDeleteRequest
	(*GetKnownNodesResponse)(nil), // 5: warehouse.GetKnownNodesResponse
	(*PulseResponse)(nil),         // 6: warehouse.PulseResponse
	(*StorageLoadResponse)(nil),   // 7: warehouse.StorageLoadResponse
	(*StorageDeleteResponse)(nil), // 8: warehouse.StorageDeleteResponse
}
var file_spec_warehouse_service_proto_depIdxs = []int32{
	0, // 0: warehouse.Warehouse.GetKnownNodes:input_type -> google.protobuf.Empty
	1, // 1: warehouse.Warehouse.PulseNodeToNode:input_type -> warehouse.PulseRequest
	2, // 2: warehouse.Warehouse.StorageStore:input_type -> warehouse.StorageStoreRequest
	3, // 3: warehouse.Warehouse.StorageLoad:input_type -> warehouse.StorageLoadRequest
	4, // 4: warehouse.Warehouse.StorageDelete:input_type -> warehouse.StorageDeleteRequest
	5, // 5: warehouse.Warehouse.GetKnownNodes:output_type -> warehouse.GetKnownNodesResponse
	6, // 6: warehouse.Warehouse.PulseNodeToNode:output_type -> warehouse.PulseResponse
	0, // 7: warehouse.Warehouse.StorageStore:output_type -> google.protobuf.Empty
	7, // 8: warehouse.Warehouse.StorageLoad:output_type -> warehouse.StorageLoadResponse
	8, // 9: warehouse.Warehouse.StorageDelete:output_type -> warehouse.StorageDeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spec_warehouse_service_proto_init() }
func file_spec_warehouse_service_proto_init() {
	if File_spec_warehouse_service_proto != nil {
		return
	}
	file_spec_warehouse_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_warehouse_service_proto_rawDesc), len(file_spec_warehouse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_warehouse_service_proto_goTypes,
		DependencyIndexes: file_spec_warehouse_service_proto_depIdxs,
	}.Build()
	File_spec_warehouse_service_proto = out.File
	file_spec_warehouse_service_proto_goTypes = nil
	file_spec_warehouse_service_proto_depIdxs = nil
}
