// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostBuyCandyHandlerFunc turns a function with the right signature into a post buy candy handler
type PostBuyCandyHandlerFunc func(PostBuyCandyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBuyCandyHandlerFunc) Handle(params PostBuyCandyParams) middleware.Responder {
	return fn(params)
}

// PostBuyCandyHandler interface for that can handle valid post buy candy params
type PostBuyCandyHandler interface {
	Handle(PostBuyCandyParams) middleware.Responder
}

// NewPostBuyCandy creates a new http.Handler for the post buy candy operation
func NewPostBuyCandy(ctx *middleware.Context, handler PostBuyCandyHandler) *PostBuyCandy {
	return &PostBuyCandy{Context: ctx, Handler: handler}
}

/*
	PostBuyCandy swagger:route POST /buy_candy postBuyCandy

PostBuyCandy post buy candy API
*/
type PostBuyCandy struct {
	Context *middleware.Context
	Handler PostBuyCandyHandler
}

func (o *PostBuyCandy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostBuyCandyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostBuyCandyBadRequestBody post buy candy bad request body
//
// swagger:model PostBuyCandyBadRequestBody
type PostBuyCandyBadRequestBody struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this post buy candy bad request body
func (o *PostBuyCandyBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post buy candy bad request body based on context it is used
func (o *PostBuyCandyBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostBuyCandyBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostBuyCandyBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostBuyCandyBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostBuyCandyBody post buy candy body
//
// swagger:model PostBuyCandyBody
type PostBuyCandyBody struct {

	// number of candy
	// Required: true
	CandyCount *int64 `json:"candyCount"`

	// kind of candy
	// Required: true
	CandyType *string `json:"candyType"`

	// amount of money put into vending machine
	// Required: true
	Money *int64 `json:"money"`
}

// Validate validates this post buy candy body
func (o *PostBuyCandyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCandyCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCandyType(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMoney(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostBuyCandyBody) validateCandyCount(formats strfmt.Registry) error {

	if err := validate.Required("order"+"."+"candyCount", "body", o.CandyCount); err != nil {
		return err
	}

	return nil
}

func (o *PostBuyCandyBody) validateCandyType(formats strfmt.Registry) error {

	if err := validate.Required("order"+"."+"candyType", "body", o.CandyType); err != nil {
		return err
	}

	return nil
}

func (o *PostBuyCandyBody) validateMoney(formats strfmt.Registry) error {

	if err := validate.Required("order"+"."+"money", "body", o.Money); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post buy candy body based on context it is used
func (o *PostBuyCandyBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostBuyCandyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostBuyCandyBody) UnmarshalBinary(b []byte) error {
	var res PostBuyCandyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostBuyCandyCreatedBody post buy candy created body
//
// swagger:model PostBuyCandyCreatedBody
type PostBuyCandyCreatedBody struct {

	// change
	Change int64 `json:"change,omitempty"`

	// thanks
	Thanks string `json:"thanks,omitempty"`
}

// Validate validates this post buy candy created body
func (o *PostBuyCandyCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post buy candy created body based on context it is used
func (o *PostBuyCandyCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostBuyCandyCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostBuyCandyCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostBuyCandyCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostBuyCandyPaymentRequiredBody post buy candy payment required body
//
// swagger:model PostBuyCandyPaymentRequiredBody
type PostBuyCandyPaymentRequiredBody struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this post buy candy payment required body
func (o *PostBuyCandyPaymentRequiredBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post buy candy payment required body based on context it is used
func (o *PostBuyCandyPaymentRequiredBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostBuyCandyPaymentRequiredBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostBuyCandyPaymentRequiredBody) UnmarshalBinary(b []byte) error {
	var res PostBuyCandyPaymentRequiredBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
