// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostBuyCandyCreatedCode is the HTTP code returned for type PostBuyCandyCreated
const PostBuyCandyCreatedCode int = 201

/*
PostBuyCandyCreated purchase successful

swagger:response postBuyCandyCreated
*/
type PostBuyCandyCreated struct {

	/*
	  In: Body
	*/
	Payload *PostBuyCandyCreatedBody `json:"body,omitempty"`
}

// NewPostBuyCandyCreated creates PostBuyCandyCreated with default headers values
func NewPostBuyCandyCreated() *PostBuyCandyCreated {

	return &PostBuyCandyCreated{}
}

// WithPayload adds the payload to the post buy candy created response
func (o *PostBuyCandyCreated) WithPayload(payload *PostBuyCandyCreatedBody) *PostBuyCandyCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post buy candy created response
func (o *PostBuyCandyCreated) SetPayload(payload *PostBuyCandyCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBuyCandyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBuyCandyBadRequestCode is the HTTP code returned for type PostBuyCandyBadRequest
const PostBuyCandyBadRequestCode int = 400

/*
PostBuyCandyBadRequest some error in input data

swagger:response postBuyCandyBadRequest
*/
type PostBuyCandyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostBuyCandyBadRequestBody `json:"body,omitempty"`
}

// NewPostBuyCandyBadRequest creates PostBuyCandyBadRequest with default headers values
func NewPostBuyCandyBadRequest() *PostBuyCandyBadRequest {

	return &PostBuyCandyBadRequest{}
}

// WithPayload adds the payload to the post buy candy bad request response
func (o *PostBuyCandyBadRequest) WithPayload(payload *PostBuyCandyBadRequestBody) *PostBuyCandyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post buy candy bad request response
func (o *PostBuyCandyBadRequest) SetPayload(payload *PostBuyCandyBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBuyCandyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBuyCandyPaymentRequiredCode is the HTTP code returned for type PostBuyCandyPaymentRequired
const PostBuyCandyPaymentRequiredCode int = 402

/*
PostBuyCandyPaymentRequired not enough money

swagger:response postBuyCandyPaymentRequired
*/
type PostBuyCandyPaymentRequired struct {

	/*
	  In: Body
	*/
	Payload *PostBuyCandyPaymentRequiredBody `json:"body,omitempty"`
}

// NewPostBuyCandyPaymentRequired creates PostBuyCandyPaymentRequired with default headers values
func NewPostBuyCandyPaymentRequired() *PostBuyCandyPaymentRequired {

	return &PostBuyCandyPaymentRequired{}
}

// WithPayload adds the payload to the post buy candy payment required response
func (o *PostBuyCandyPaymentRequired) WithPayload(payload *PostBuyCandyPaymentRequiredBody) *PostBuyCandyPaymentRequired {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post buy candy payment required response
func (o *PostBuyCandyPaymentRequired) SetPayload(payload *PostBuyCandyPaymentRequiredBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBuyCandyPaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(402)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
