// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: spec/warehouse-service.proto

package warehousepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Warehouse_GetKnownNodes_FullMethodName       = "/warehouse.Warehouse/GetKnownNodes"
	Warehouse_PulseNodeToNode_FullMethodName     = "/warehouse.Warehouse/PulseNodeToNode"
	Warehouse_StorageStore_FullMethodName        = "/warehouse.Warehouse/StorageStore"
	Warehouse_StorageLoad_FullMethodName         = "/warehouse.Warehouse/StorageLoad"
	Warehouse_StorageDelete_FullMethodName       = "/warehouse.Warehouse/StorageDelete"
	Warehouse_ClientGetNodes_FullMethodName      = "/warehouse.Warehouse/ClientGetNodes"
	Warehouse_ClientStorageStore_FullMethodName  = "/warehouse.Warehouse/ClientStorageStore"
	Warehouse_ClientStorageLoad_FullMethodName   = "/warehouse.Warehouse/ClientStorageLoad"
	Warehouse_ClientStorageDelete_FullMethodName = "/warehouse.Warehouse/ClientStorageDelete"
	Warehouse_FixMesh_FullMethodName             = "/warehouse.Warehouse/FixMesh"
)

// WarehouseClient is the client API for Warehouse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarehouseClient interface {
	GetKnownNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetKnownNodesResponse, error)
	PulseNodeToNode(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (*PulseResponse, error)
	StorageStore(ctx context.Context, in *StorageStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StorageLoad(ctx context.Context, in *StorageLoadRequest, opts ...grpc.CallOption) (*StorageLoadResponse, error)
	StorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error)
	ClientGetNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClientGetNodesResponse, error)
	ClientStorageStore(ctx context.Context, in *StorageStoreRequest, opts ...grpc.CallOption) (*ClientStorageStoreResponse, error)
	ClientStorageLoad(ctx context.Context, in *StorageLoadRequest, opts ...grpc.CallOption) (*StorageLoadResponse, error)
	ClientStorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*ClientStorageDeleteResponse, error)
	FixMesh(ctx context.Context, in *FixMeshRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type warehouseClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseClient(cc grpc.ClientConnInterface) WarehouseClient {
	return &warehouseClient{cc}
}

func (c *warehouseClient) GetKnownNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetKnownNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnownNodesResponse)
	err := c.cc.Invoke(ctx, Warehouse_GetKnownNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) PulseNodeToNode(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (*PulseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PulseResponse)
	err := c.cc.Invoke(ctx, Warehouse_PulseNodeToNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) StorageStore(ctx context.Context, in *StorageStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Warehouse_StorageStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) StorageLoad(ctx context.Context, in *StorageLoadRequest, opts ...grpc.CallOption) (*StorageLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageLoadResponse)
	err := c.cc.Invoke(ctx, Warehouse_StorageLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) StorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDeleteResponse)
	err := c.cc.Invoke(ctx, Warehouse_StorageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) ClientGetNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClientGetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientGetNodesResponse)
	err := c.cc.Invoke(ctx, Warehouse_ClientGetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) ClientStorageStore(ctx context.Context, in *StorageStoreRequest, opts ...grpc.CallOption) (*ClientStorageStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientStorageStoreResponse)
	err := c.cc.Invoke(ctx, Warehouse_ClientStorageStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) ClientStorageLoad(ctx context.Context, in *StorageLoadRequest, opts ...grpc.CallOption) (*StorageLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageLoadResponse)
	err := c.cc.Invoke(ctx, Warehouse_ClientStorageLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) ClientStorageDelete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*ClientStorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientStorageDeleteResponse)
	err := c.cc.Invoke(ctx, Warehouse_ClientStorageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseClient) FixMesh(ctx context.Context, in *FixMeshRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Warehouse_FixMesh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServer is the server API for Warehouse service.
// All implementations must embed UnimplementedWarehouseServer
// for forward compatibility.
type WarehouseServer interface {
	GetKnownNodes(context.Context, *emptypb.Empty) (*GetKnownNodesResponse, error)
	PulseNodeToNode(context.Context, *PulseRequest) (*PulseResponse, error)
	StorageStore(context.Context, *StorageStoreRequest) (*emptypb.Empty, error)
	StorageLoad(context.Context, *StorageLoadRequest) (*StorageLoadResponse, error)
	StorageDelete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error)
	ClientGetNodes(context.Context, *emptypb.Empty) (*ClientGetNodesResponse, error)
	ClientStorageStore(context.Context, *StorageStoreRequest) (*ClientStorageStoreResponse, error)
	ClientStorageLoad(context.Context, *StorageLoadRequest) (*StorageLoadResponse, error)
	ClientStorageDelete(context.Context, *StorageDeleteRequest) (*ClientStorageDeleteResponse, error)
	FixMesh(context.Context, *FixMeshRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWarehouseServer()
}

// UnimplementedWarehouseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseServer struct{}

func (UnimplementedWarehouseServer) GetKnownNodes(context.Context, *emptypb.Empty) (*GetKnownNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnownNodes not implemented")
}
func (UnimplementedWarehouseServer) PulseNodeToNode(context.Context, *PulseRequest) (*PulseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PulseNodeToNode not implemented")
}
func (UnimplementedWarehouseServer) StorageStore(context.Context, *StorageStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageStore not implemented")
}
func (UnimplementedWarehouseServer) StorageLoad(context.Context, *StorageLoadRequest) (*StorageLoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageLoad not implemented")
}
func (UnimplementedWarehouseServer) StorageDelete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageDelete not implemented")
}
func (UnimplementedWarehouseServer) ClientGetNodes(context.Context, *emptypb.Empty) (*ClientGetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientGetNodes not implemented")
}
func (UnimplementedWarehouseServer) ClientStorageStore(context.Context, *StorageStoreRequest) (*ClientStorageStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientStorageStore not implemented")
}
func (UnimplementedWarehouseServer) ClientStorageLoad(context.Context, *StorageLoadRequest) (*StorageLoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientStorageLoad not implemented")
}
func (UnimplementedWarehouseServer) ClientStorageDelete(context.Context, *StorageDeleteRequest) (*ClientStorageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientStorageDelete not implemented")
}
func (UnimplementedWarehouseServer) FixMesh(context.Context, *FixMeshRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FixMesh not implemented")
}
func (UnimplementedWarehouseServer) mustEmbedUnimplementedWarehouseServer() {}
func (UnimplementedWarehouseServer) testEmbeddedByValue()                   {}

// UnsafeWarehouseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServer will
// result in compilation errors.
type UnsafeWarehouseServer interface {
	mustEmbedUnimplementedWarehouseServer()
}

func RegisterWarehouseServer(s grpc.ServiceRegistrar, srv WarehouseServer) {
	// If the following call pancis, it indicates UnimplementedWarehouseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Warehouse_ServiceDesc, srv)
}

func _Warehouse_GetKnownNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).GetKnownNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_GetKnownNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).GetKnownNodes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_PulseNodeToNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PulseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).PulseNodeToNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_PulseNodeToNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).PulseNodeToNode(ctx, req.(*PulseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_StorageStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).StorageStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_StorageStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).StorageStore(ctx, req.(*StorageStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_StorageLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).StorageLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_StorageLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).StorageLoad(ctx, req.(*StorageLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_StorageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).StorageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_StorageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).StorageDelete(ctx, req.(*StorageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_ClientGetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).ClientGetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_ClientGetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).ClientGetNodes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_ClientStorageStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).ClientStorageStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_ClientStorageStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).ClientStorageStore(ctx, req.(*StorageStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_ClientStorageLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).ClientStorageLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_ClientStorageLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).ClientStorageLoad(ctx, req.(*StorageLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_ClientStorageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).ClientStorageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_ClientStorageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).ClientStorageDelete(ctx, req.(*StorageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warehouse_FixMesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FixMeshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServer).FixMesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Warehouse_FixMesh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServer).FixMesh(ctx, req.(*FixMeshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Warehouse_ServiceDesc is the grpc.ServiceDesc for Warehouse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Warehouse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.Warehouse",
	HandlerType: (*WarehouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKnownNodes",
			Handler:    _Warehouse_GetKnownNodes_Handler,
		},
		{
			MethodName: "PulseNodeToNode",
			Handler:    _Warehouse_PulseNodeToNode_Handler,
		},
		{
			MethodName: "StorageStore",
			Handler:    _Warehouse_StorageStore_Handler,
		},
		{
			MethodName: "StorageLoad",
			Handler:    _Warehouse_StorageLoad_Handler,
		},
		{
			MethodName: "StorageDelete",
			Handler:    _Warehouse_StorageDelete_Handler,
		},
		{
			MethodName: "ClientGetNodes",
			Handler:    _Warehouse_ClientGetNodes_Handler,
		},
		{
			MethodName: "ClientStorageStore",
			Handler:    _Warehouse_ClientStorageStore_Handler,
		},
		{
			MethodName: "ClientStorageLoad",
			Handler:    _Warehouse_ClientStorageLoad_Handler,
		},
		{
			MethodName: "ClientStorageDelete",
			Handler:    _Warehouse_ClientStorageDelete_Handler,
		},
		{
			MethodName: "FixMesh",
			Handler:    _Warehouse_FixMesh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spec/warehouse-service.proto",
}
