// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: spec/warehouse.proto

package warehousepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUuid      string                 `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_spec_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PulseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requester     *Node                  `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseRequest) Reset() {
	*x = PulseRequest{}
	mi := &file_spec_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseRequest) ProtoMessage() {}

func (x *PulseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseRequest.ProtoReflect.Descriptor instead.
func (*PulseRequest) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *PulseRequest) GetRequester() *Node {
	if x != nil {
		return x.Requester
	}
	return nil
}

type PulseResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Respondent            *Node                  `protobuf:"bytes,1,opt,name=respondent,proto3" json:"respondent,omitempty"`
	RespondentPulsePeriod string                 `protobuf:"bytes,3,opt,name=respondent_pulse_period,json=respondentPulsePeriod,proto3" json:"respondent_pulse_period,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PulseResponse) Reset() {
	*x = PulseResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseResponse) ProtoMessage() {}

func (x *PulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseResponse.ProtoReflect.Descriptor instead.
func (*PulseResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *PulseResponse) GetRespondent() *Node {
	if x != nil {
		return x.Respondent
	}
	return nil
}

func (x *PulseResponse) GetRespondentPulsePeriod() string {
	if x != nil {
		return x.RespondentPulsePeriod
	}
	return ""
}

type GetKnownNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pulse         *durationpb.Duration   `protobuf:"bytes,2,opt,name=pulse,proto3" json:"pulse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnownNodesResponse) Reset() {
	*x = GetKnownNodesResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnownNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnownNodesResponse) ProtoMessage() {}

func (x *GetKnownNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnownNodesResponse.ProtoReflect.Descriptor instead.
func (*GetKnownNodesResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *GetKnownNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetKnownNodesResponse) GetPulse() *durationpb.Duration {
	if x != nil {
		return x.Pulse
	}
	return nil
}

type StorageStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStoreRequest) Reset() {
	*x = StorageStoreRequest{}
	mi := &file_spec_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStoreRequest) ProtoMessage() {}

func (x *StorageStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStoreRequest.ProtoReflect.Descriptor instead.
func (*StorageStoreRequest) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *StorageStoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageStoreRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StorageLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageLoadRequest) Reset() {
	*x = StorageLoadRequest{}
	mi := &file_spec_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageLoadRequest) ProtoMessage() {}

func (x *StorageLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageLoadRequest.ProtoReflect.Descriptor instead.
func (*StorageLoadRequest) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *StorageLoadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StorageLoadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Types that are valid to be assigned to ValuePresent:
	//
	//	*StorageLoadResponse_Value
	ValuePresent  isStorageLoadResponse_ValuePresent `protobuf_oneof:"value_present"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageLoadResponse) Reset() {
	*x = StorageLoadResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageLoadResponse) ProtoMessage() {}

func (x *StorageLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageLoadResponse.ProtoReflect.Descriptor instead.
func (*StorageLoadResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{6}
}

func (x *StorageLoadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *StorageLoadResponse) GetValuePresent() isStorageLoadResponse_ValuePresent {
	if x != nil {
		return x.ValuePresent
	}
	return nil
}

func (x *StorageLoadResponse) GetValue() string {
	if x != nil {
		if x, ok := x.ValuePresent.(*StorageLoadResponse_Value); ok {
			return x.Value
		}
	}
	return ""
}

type isStorageLoadResponse_ValuePresent interface {
	isStorageLoadResponse_ValuePresent()
}

type StorageLoadResponse_Value struct {
	Value string `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*StorageLoadResponse_Value) isStorageLoadResponse_ValuePresent() {}

type StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_spec_warehouse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{7}
}

func (x *StorageDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{8}
}

func (x *StorageDeleteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ClientGetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Leader        *Node                  `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetNodesResponse) Reset() {
	*x = ClientGetNodesResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetNodesResponse) ProtoMessage() {}

func (x *ClientGetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetNodesResponse.ProtoReflect.Descriptor instead.
func (*ClientGetNodesResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{9}
}

func (x *ClientGetNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClientGetNodesResponse) GetLeader() *Node {
	if x != nil {
		return x.Leader
	}
	return nil
}

type FixMeshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaFactor int32                  `protobuf:"varint,1,opt,name=replica_factor,json=replicaFactor,proto3" json:"replica_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixMeshRequest) Reset() {
	*x = FixMeshRequest{}
	mi := &file_spec_warehouse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixMeshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixMeshRequest) ProtoMessage() {}

func (x *FixMeshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixMeshRequest.ProtoReflect.Descriptor instead.
func (*FixMeshRequest) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{10}
}

func (x *FixMeshRequest) GetReplicaFactor() int32 {
	if x != nil {
		return x.ReplicaFactor
	}
	return 0
}

type ClientStorageStoreResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StoredReplicas int32                  `protobuf:"varint,1,opt,name=stored_replicas,json=storedReplicas,proto3" json:"stored_replicas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientStorageStoreResponse) Reset() {
	*x = ClientStorageStoreResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStorageStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStorageStoreResponse) ProtoMessage() {}

func (x *ClientStorageStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStorageStoreResponse.ProtoReflect.Descriptor instead.
func (*ClientStorageStoreResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{11}
}

func (x *ClientStorageStoreResponse) GetStoredReplicas() int32 {
	if x != nil {
		return x.StoredReplicas
	}
	return 0
}

type ClientStorageDeleteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeletedReplicas int32                  `protobuf:"varint,1,opt,name=deleted_replicas,json=deletedReplicas,proto3" json:"deleted_replicas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientStorageDeleteResponse) Reset() {
	*x = ClientStorageDeleteResponse{}
	mi := &file_spec_warehouse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStorageDeleteResponse) ProtoMessage() {}

func (x *ClientStorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_warehouse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*ClientStorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_spec_warehouse_proto_rawDescGZIP(), []int{12}
}

func (x *ClientStorageDeleteResponse) GetDeletedReplicas() int32 {
	if x != nil {
		return x.DeletedReplicas
	}
	return 0
}

var File_spec_warehouse_proto protoreflect.FileDescriptor

const file_spec_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x14spec/warehouse.proto\x12\twarehouse\x1a\x1egoogle/protobuf/duration.proto\"=\n" +
	"\x04Node\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"=\n" +
	"\fPulseRequest\x12-\n" +
	"\trequester\x18\x01 \x01(\v2\x0f.warehouse.NodeR\trequester\"x\n" +
	"\rPulseResponse\x12/\n" +
	"\n" +
	"respondent\x18\x01 \x01(\v2\x0f.warehouse.NodeR\n" +
	"respondent\x126\n" +
	"\x17respondent_pulse_period\x18\x03 \x01(\tR\x15respondentPulsePeriod\"o\n" +
	"\x15GetKnownNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.warehouse.NodeR\x05nodes\x12/\n" +
	"\x05pulse\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05pulse\"=\n" +
	"\x13StorageStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"&\n" +
	"\x12StorageLoadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"T\n" +
	"\x13StorageLoadResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x16\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05valueB\x0f\n" +
	"\rvalue_present\"(\n" +
	"\x14StorageDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"-\n" +
	"\x15StorageDeleteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\"h\n" +
	"\x16ClientGetNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.warehouse.NodeR\x05nodes\x12'\n" +
	"\x06leader\x18\x02 \x01(\v2\x0f.warehouse.NodeR\x06leader\"7\n" +
	"\x0eFixMeshRequest\x12%\n" +
	"\x0ereplica_factor\x18\x01 \x01(\x05R\rreplicaFactor\"E\n" +
	"\x1aClientStorageStoreResponse\x12'\n" +
	"\x0fstored_replicas\x18\x01 \x01(\x05R\x0estoredReplicas\"H\n" +
	"\x1bClientStorageDeleteResponse\x12)\n" +
	"\x10deleted_replicas\x18\x01 \x01(\x05R\x0fdeletedReplicasB\x1dZ\x1bpkg/service/api/warehousepbb\x06proto3"

var (
	file_spec_warehouse_proto_rawDescOnce sync.Once
	file_spec_warehouse_proto_rawDescData []byte
)

func file_spec_warehouse_proto_rawDescGZIP() []byte {
	file_spec_warehouse_proto_rawDescOnce.Do(func() {
		file_spec_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_warehouse_proto_rawDesc), len(file_spec_warehouse_proto_rawDesc)))
	})
	return file_spec_warehouse_proto_rawDescData
}

var file_spec_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_spec_warehouse_proto_goTypes = []any{
	(*Node)(nil),                        // 0: warehouse.Node
	(*PulseRequest)(nil),                // 1: warehouse.PulseRequest
	(*PulseResponse)(nil),               // 2: warehouse.PulseResponse
	(*GetKnownNodesResponse)(nil),       // 3: warehouse.GetKnownNodesResponse
	(*StorageStoreRequest)(nil),         // 4: warehouse.StorageStoreRequest
	(*StorageLoadRequest)(nil),          // 5: warehouse.StorageLoadRequest
	(*StorageLoadResponse)(nil),         // 6: warehouse.StorageLoadResponse
	(*StorageDeleteRequest)(nil),        // 7: warehouse.StorageDeleteRequest
	(*StorageDeleteResponse)(nil),       // 8: warehouse.StorageDeleteResponse
	(*ClientGetNodesResponse)(nil),      // 9: warehouse.ClientGetNodesResponse
	(*FixMeshRequest)(nil),              // 10: warehouse.FixMeshRequest
	(*ClientStorageStoreResponse)(nil),  // 11: warehouse.ClientStorageStoreResponse
	(*ClientStorageDeleteResponse)(nil), // 12: warehouse.ClientStorageDeleteResponse
	(*durationpb.Duration)(nil),         // 13: google.protobuf.Duration
}
var file_spec_warehouse_proto_depIdxs = []int32{
	0,  // 0: warehouse.PulseRequest.requester:type_name -> warehouse.Node
	0,  // 1: warehouse.PulseResponse.respondent:type_name -> warehouse.Node
	0,  // 2: warehouse.GetKnownNodesResponse.nodes:type_name -> warehouse.Node
	13, // 3: warehouse.GetKnownNodesResponse.pulse:type_name -> google.protobuf.Duration
	0,  // 4: warehouse.ClientGetNodesResponse.nodes:type_name -> warehouse.Node
	0,  // 5: warehouse.ClientGetNodesResponse.leader:type_name -> warehouse.Node
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_spec_warehouse_proto_init() }
func file_spec_warehouse_proto_init() {
	if File_spec_warehouse_proto != nil {
		return
	}
	file_spec_warehouse_proto_msgTypes[6].OneofWrappers = []any{
		(*StorageLoadResponse_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_warehouse_proto_rawDesc), len(file_spec_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_warehouse_proto_goTypes,
		DependencyIndexes: file_spec_warehouse_proto_depIdxs,
		MessageInfos:      file_spec_warehouse_proto_msgTypes,
	}.Build()
	File_spec_warehouse_proto = out.File
	file_spec_warehouse_proto_goTypes = nil
	file_spec_warehouse_proto_depIdxs = nil
}
