// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	restapi2 "4/ex00/restapi"
	"4/ex00/restapi/operations"
	"github.com/jessevdk/go-flags"
	"log"
	"os"

	"github.com/go-openapi/loads"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi2.SwaggerJSON, restapi2.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewCandyServerAPI(swaggerSpec)
	server := restapi2.NewServer(api)
	defer server.Shutdown()

	server.Port = 3333

	//Настройка маршрутов
	//api.PostBuyCandyHandler = operations.PostBuyCandyHandlerFunc(handler.BuyCandyHandler)

	//if err := server.Serve(); err != nil {
	//	log.Fatalln(err)
	//}

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Candy Server"
	parser.LongDescription = swaggerSpec.Spec().Info.Description
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}